const express = require('express');
const stripe = require('stripe')(process.env.STRIPE_SECRET_KEY);
const axios = require('axios');
const { generateBinancePayHeaders } = require('../utilities/binancePayUtils');
const { logger } = require('../utilities/logger');
require('dotenv').config();
const router = express.Router();
const db = require('../database');

const ADMINISTRATION_AND_ONE_YEAR_SIGNAL_FEE = 15;
const STRIPE_PROCESSING_FEE_PERCENTAGE = 4.2 / 100;

function calculateTotalCharge(productPrice) {
	const flatFee = 1.0;

	return Math.ceil((productPrice + flatFee) / (1 - STRIPE_PROCESSING_FEE_PERCENTAGE));
}

// Stripe payment endpoint
router.get('/get-products/:currentPlan', async (req, res) => {
	const { currentPlan } = req.params;

	const isCurrentPlanAnInteger = Number.isInteger(parseInt(currentPlan));

	const plan = isCurrentPlanAnInteger ? parseInt(currentPlan) + 1 : 1;
	const result = await db.query('SELECT * FROM products WHERE id = ?', [plan]);

	const planData = result[0];

	const administrationFee = isCurrentPlanAnInteger ? 0 : ADMINISTRATION_AND_ONE_YEAR_SIGNAL_FEE;

	const total = planData.product_price + administrationFee;

	const fullTotal = calculateTotalCharge(total);

	res.json({
		...planData,
		administrationFee,
		total: fullTotal,
		stripeTotal: fullTotal * 100,
	});
});

router.post('/create-payment-intent', async (req, res) => {
	const { firstName, lastName, email, address, amount, description } = req.body; // 'source' is the token id generated by Stripe on the frontend
	try {
		const customer = await stripe.customers.create({ name: `${firstName} ${lastName}`, email });

		const paymentIntent = await stripe.paymentIntents.create({
			amount: amount,
			currency: 'usd',
			description: 'Forex Trading Master Course, including Administration Fee and 1-Year Signal Service.',
			automatic_payment_methods: {
				enabled: true,
			},
			customer: customer.id,
		});
		res.json({ success: true, clientSecret: paymentIntent.client_secret });
	} catch (error) {
		logger.error('Stripe Charge Error:', error);
		res.status(500).json({ success: false, error: error.message });
	}
});

router.get('/verify-payment', async (req, res) => {
	const {
		payment_intent,
		payment_intent_client_secret,
		redirect_status,
		member_id,
		introducer,
		plan,
		referral_points,
		referral_type,
		amount,
	} = req.query;

	try {
		const result1 = await db.query(
			'UPDATE `fx_users` SET profile_status = ?, activation_date = NOW(), plan = ? WHERE member_id = ?',
			['Activated', parseInt(plan), parseInt(member_id)]
		);
		const result2 = await db.query(
			'INSERT INTO transactions(amount, payment_intent, member_id, plan) VALUES (?, ?, ?, ?)',
			[parseFloat(amount), payment_intent, parseInt(member_id), parseInt(plan)]
		);

		// TODO introducer

		res.json({ success: true });
	} catch (error) {
		console.error(error);
		res.json({ status: 500, message: error.message });
	}
});

// Binance Pay payment endpoint (Corrected and updated version)
router.post('/binancepay', async (req, res) => {
	const requestBody = JSON.stringify(req.body);
	const apiKey = process.env.BINANCE_PAY_CERTIFICATE_SN;
	const secretKey = process.env.BINANCE_PAY_SECRET_KEY;

	const headers = generateBinancePayHeaders(apiKey, secretKey, requestBody);

	try {
		// Ensure you're using the correct Binance Pay URL and endpoint
		const response = await axios.post('https://bpay.binanceapi.com/binancepay/openapi/v1/order', requestBody, {
			headers,
		});
		res.json(response.data);
	} catch (error) {
		logger.error('Error making Binance Pay request:', error.response ? error.response.data : error);
		res.status(500).json({ message: 'Failed to process payment with Binance Pay' });
	}
});

module.exports = router;
